import { 
  UserProfile, FarmerProfile, IndustryProfile, AuctionLot, AnonymousBid, 
  AuctionRegistration, GroundVerification, DealAgreement, DeliveryRecord, 
  AuditLog, AppNotification, PlatformSettings 
} from '@/types';

export const INITIAL_PLATFORM_SETTINGS: PlatformSettings = {
  industryRegistrationFeeInr: 1999,
  cancellationFeeInr: 5000,
  minimumBidIncrementInr: 500,
  sampleMinimumWeightKg: 20,
  auctionDurationHours: 24,
  winnerResponseWindowDays: 3,
  maxFallbackBidders: 3,
  sangliHubAddress: 'CropLink Agri-Hub, Plot 42, APMC Market Yard, Sangli, Maharashtra - 416416',
};

// Demo Users
export const DEMO_PROFILES: UserProfile[] = [
  {
    id: 'usr_farmer_1',
    email: 'farmer@croplink.demo',
    role: 'FARMER',
    status: 'APPROVED',
    fullName: 'Rameshwar Patil',
    mobile: '+91 98230 12345',
    createdAt: '2026-08-01T10:00:00Z',
    updatedAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'usr_industry_1',
    email: 'industry@croplink.demo',
    role: 'INDUSTRY',
    status: 'APPROVED',
    fullName: 'Sunil Deshmukh (AgriFoods India Ltd)',
    mobile: '+91 98190 98765',
    createdAt: '2026-08-02T11:30:00Z',
    updatedAt: '2026-08-02T11:30:00Z',
  },
  {
    id: 'usr_admin_1',
    email: 'admin@croplink.demo',
    role: 'ADMIN',
    status: 'APPROVED',
    fullName: 'CropLink Admin Operations',
    mobile: '+91 99000 00000',
    createdAt: '2026-07-15T09:00:00Z',
    updatedAt: '2026-07-15T09:00:00Z',
  },
];

export const DEMO_FARMER_PROFILE: FarmerProfile = {
  id: 'fp_1',
  userId: 'usr_farmer_1',
  fullAddress: 'Gat No. 142, Tasgaon Road, Kupwad, Sangli',
  village: 'Kupwad',
  district: 'Sangli',
  state: 'Maharashtra',
  pincode: '416436',
  farmName: 'Patil Bio-Organic Farms',
  farmLocation: 'Sangli Rural',
  landAreaAcres: 18.5,
  cropsGrown: ['Turmeric', 'Grapes', 'Sugarcane'],
  farmerDocUrl: 'https://croplink.demo/docs/farmer_789.pdf',
  identityDocUrl: 'https://croplink.demo/docs/aadhaar_patil.pdf',
  coordinates: { lat: 16.8524, lng: 74.5815 },
};

export const DEMO_INDUSTRY_PROFILE: IndustryProfile = {
  id: 'ip_1',
  userId: 'usr_industry_1',
  companyName: 'AgriFoods Spices & Processing India Ltd',
  gstNumber: '27AAAAA0000A1Z5',
  contactPerson: 'Sunil Deshmukh',
  fullAddress: 'Plot C-12, MIDC Industrial Area, Thane West, Mumbai',
  city: 'Mumbai',
  state: 'Maharashtra',
  pincode: '400604',
  industryType: 'Food & Spice Processing Manufacturer',
  requiredCrops: ['Turmeric', 'Onion', 'Tomato'],
  requiredQuantityTons: 250,
  preferredQualityGrade: 'Grade A Export Quality',
  procurementLocation: 'Western Maharashtra',
  registrationDocUrl: 'https://croplink.demo/docs/gst_agrifoods.pdf',
  gstDocUrl: 'https://croplink.demo/docs/cin_agrifoods.pdf',
  coordinates: { lat: 19.0760, lng: 72.8777 },
};

// Initial Demo Auctions
export const DEMO_AUCTIONS: AuctionLot[] = [
  {
    id: 'auc_1',
    farmerId: 'usr_farmer_1',
    farmerAnonymousId: 'Farmer #MH-42 (Sangli)',
    crop: 'Turmeric (हल्दी)',
    variety: 'Rajapuri High-Curcumin',
    quantityTons: 25,
    qualityGrade: 'Grade A+ (Curcumin 4.8%)',
    harvestDate: '2026-09-10',
    locationArea: 'Kupwad, Sangli District',
    description: 'Sun-dried premium Rajapuri turmeric fingers with high curcumin content. Cleaned and graded at farm.',
    basePricePerTon: 150000,
    transportPricePer100Km: 600,
    registrationDurationDays: 4,
    sampleStatus: 'VERIFIED',
    status: 'AUCTION_LIVE',
    createdAt: '2026-09-12T10:00:00Z',
    registrationEndsAt: '2026-09-16T10:00:00Z',
    sampleProcessingEndsAt: '2026-09-19T10:00:00Z',
    auctionStartsAt: '2026-09-18T00:00:00Z',
    auctionEndsAt: '2026-09-19T00:00:00Z',
    currentHighestBid: 162000,
    bidCount: 4,
  },
  {
    id: 'auc_2',
    farmerId: 'usr_farmer_1',
    farmerAnonymousId: 'Farmer #MH-42 (Sangli)',
    crop: 'Onion (प्याज)',
    variety: 'Red Garwa Export Grade',
    quantityTons: 50,
    qualityGrade: 'Grade A (55mm+ Size)',
    harvestDate: '2026-09-05',
    locationArea: 'Lasalgaon, Nashik District',
    description: 'Dry cured red onions stored in ventilated storage. Zero rot, ready for bulk container loading.',
    basePricePerTon: 25000,
    transportPricePer100Km: 500,
    registrationDurationDays: 3,
    sampleStatus: 'FORWARDED_TO_INDUSTRY',
    status: 'AUCTION_LIVE',
    createdAt: '2026-09-13T08:00:00Z',
    registrationEndsAt: '2026-09-16T08:00:00Z',
    sampleProcessingEndsAt: '2026-09-19T08:00:00Z',
    auctionStartsAt: '2026-09-18T02:00:00Z',
    auctionEndsAt: '2026-09-19T02:00:00Z',
    currentHighestBid: 28500,
    bidCount: 3,
  },
  {
    id: 'auc_3',
    farmerId: 'usr_farmer_2',
    farmerAnonymousId: 'Farmer #MH-18 (Nashik)',
    crop: 'Tomato (टमाटर)',
    variety: 'Hybrid Abhinav Firm',
    quantityTons: 15,
    qualityGrade: 'Grade A',
    harvestDate: '2026-09-14',
    locationArea: 'Khed, Pune District',
    description: 'Firm red tomatoes suitable for paste and ketchup manufacturing. Uniform color.',
    basePricePerTon: 22000,
    transportPricePer100Km: 450,
    registrationDurationDays: 5,
    sampleStatus: 'RECEIVED',
    status: 'REGISTRATION_OPEN',
    createdAt: '2026-09-15T12:00:00Z',
    registrationEndsAt: '2026-09-20T12:00:00Z',
    sampleProcessingEndsAt: '2026-09-23T12:00:00Z',
    auctionStartsAt: '2026-09-24T09:00:00Z',
    auctionEndsAt: '2026-09-25T09:00:00Z',
    currentHighestBid: 0,
    bidCount: 0,
  },
  {
    id: 'auc_4',
    farmerId: 'usr_farmer_1',
    farmerAnonymousId: 'Farmer #MH-42 (Sangli)',
    crop: 'Pomegranate (अनार)',
    variety: 'Bhagwa Dark Red',
    quantityTons: 20,
    qualityGrade: 'Grade A+ Export',
    harvestDate: '2026-09-01',
    locationArea: 'Solapur Rural',
    description: 'Deep red Bhagwa pomegranates, average weight 300g+ per fruit. High brix sweetness.',
    basePricePerTon: 105000,
    transportPricePer100Km: 550,
    registrationDurationDays: 3,
    sampleStatus: 'VERIFIED',
    status: 'WINNER_PENDING_VERIFICATION',
    createdAt: '2026-09-08T09:00:00Z',
    registrationEndsAt: '2026-09-11T09:00:00Z',
    sampleProcessingEndsAt: '2026-09-14T09:00:00Z',
    auctionStartsAt: '2026-09-15T09:00:00Z',
    auctionEndsAt: '2026-09-16T09:00:00Z',
    currentHighestBid: 118000,
    bidCount: 5,
    winningBidId: 'bid_4_1',
    winnerIndustryId: 'usr_industry_1',
    activeRankBidderIndex: 0,
    winnerResponseDeadline: '2026-09-19T09:00:00Z',
  },
];

// Initial Bids for Demo Auctions
export const DEMO_BIDS: AnonymousBid[] = [
  // Bids for Turmeric (auc_1)
  {
    id: 'bid_1_1',
    auctionId: 'auc_1',
    industryId: 'usr_industry_2',
    anonymousBidderId: 'Bidder #B04',
    amountPerTon: 153000,
    totalAmount: 3825000,
    createdAt: '2026-09-17T11:00:00Z',
    status: 'OUTBID',
  },
  {
    id: 'bid_1_2',
    auctionId: 'auc_1',
    industryId: 'usr_industry_3',
    anonymousBidderId: 'Bidder #C89',
    amountPerTon: 157000,
    totalAmount: 3925000,
    createdAt: '2026-09-17T13:30:00Z',
    status: 'OUTBID',
  },
  {
    id: 'bid_1_3',
    auctionId: 'auc_1',
    industryId: 'usr_industry_1',
    anonymousBidderId: 'Bidder #A17',
    amountPerTon: 162000,
    totalAmount: 4050000,
    createdAt: '2026-09-17T16:45:00Z',
    status: 'ACTIVE',
  },

  // Bids for Onion (auc_2)
  {
    id: 'bid_2_1',
    auctionId: 'auc_2',
    industryId: 'usr_industry_1',
    anonymousBidderId: 'Bidder #A17',
    amountPerTon: 28500,
    totalAmount: 1425000,
    createdAt: '2026-09-17T14:10:00Z',
    status: 'ACTIVE',
  },

  // Bids for Pomegranate (auc_4)
  {
    id: 'bid_4_1',
    auctionId: 'auc_4',
    industryId: 'usr_industry_1',
    anonymousBidderId: 'Bidder #A17',
    amountPerTon: 118000,
    totalAmount: 2360000,
    createdAt: '2026-09-15T15:00:00Z',
    status: 'WINNER_SELECTED',
  },
  {
    id: 'bid_4_2',
    auctionId: 'auc_4',
    industryId: 'usr_industry_4',
    anonymousBidderId: 'Bidder #D52',
    amountPerTon: 114000,
    totalAmount: 2280000,
    createdAt: '2026-09-15T14:20:00Z',
    status: 'OUTBID',
  },
  {
    id: 'bid_4_3',
    auctionId: 'auc_4',
    industryId: 'usr_industry_5',
    anonymousBidderId: 'Bidder #E91',
    amountPerTon: 109000,
    totalAmount: 2180000,
    createdAt: '2026-09-15T11:00:00Z',
    status: 'OUTBID',
  },
];

export const DEMO_REGISTRATIONS: AuctionRegistration[] = [
  {
    id: 'reg_1',
    auctionId: 'auc_1',
    industryId: 'usr_industry_1',
    paymentId: 'pay_demo_1',
    feeAmount: 1999,
    status: 'PAID',
    createdAt: '2026-09-13T10:00:00Z',
  },
  {
    id: 'reg_2',
    auctionId: 'auc_2',
    industryId: 'usr_industry_1',
    paymentId: 'pay_demo_2',
    feeAmount: 1999,
    status: 'PAID',
    createdAt: '2026-09-14T11:00:00Z',
  },
  {
    id: 'reg_4',
    auctionId: 'auc_4',
    industryId: 'usr_industry_1',
    paymentId: 'pay_demo_4',
    feeAmount: 1999,
    status: 'PAID',
    createdAt: '2026-09-09T09:00:00Z',
  },
];

export const DEMO_VERIFICATIONS: GroundVerification[] = [
  {
    id: 'gv_4',
    auctionId: 'auc_4',
    industryId: 'usr_industry_1',
    assignedBidderRank: 1,
    scheduledDate: '2026-09-18',
    status: 'REQUESTED',
    notes: 'Ground quality inspector assigned to visit farm in Solapur for size and moisture validation.',
    updatedAt: '2026-09-16T09:30:00Z',
  },
];

export const DEMO_AGREEMENTS: DealAgreement[] = [
  {
    id: 'agr_comp_1',
    auctionId: 'auc_historic_1',
    farmerId: 'usr_farmer_1',
    industryId: 'usr_industry_1',
    crop: 'Turmeric (हल्दी)',
    quantityTons: 10,
    finalPricePerTon: 148000,
    totalDealValue: 1480000,
    agreedAt: '2026-08-15T14:00:00Z',
    farmerSignature: 'Rameshwar Patil (Digitally Signed)',
    farmerSignedAt: '2026-08-15T15:20:00Z',
    industrySignature: 'Sunil Deshmukh (AgriFoods India)',
    industrySignedAt: '2026-08-15T16:00:00Z',
    terms: '1. CropLink Verified Sample Match Guarantee\n2. Transportation arranged by buyer via CropLink Logistics\n3. Full payment released upon warehouse receipt verification.',
    status: 'FULLY_EXECUTED',
  },
];

export const DEMO_DELIVERIES: DeliveryRecord[] = [
  {
    id: 'del_1',
    dealId: 'agr_comp_1',
    auctionId: 'auc_historic_1',
    originArea: 'Sangli Rural, Maharashtra',
    destinationArea: 'MIDC Thane West, Mumbai',
    estimatedKm: 380,
    status: 'IN_TRANSIT',
    driverName: 'Suresh More',
    driverPhone: '+91 97654 32109',
    vehicleNumber: 'MH 10 CR 4582',
    expectedDeliveryDate: '2026-09-19',
    timeline: [
      { status: 'ORDER_CONFIRMED', timestamp: '2026-09-16T10:00:00Z', location: 'CropLink Hub Sangli', note: 'Agreement signed and transport truck assigned.' },
      { status: 'PICKED_UP', timestamp: '2026-09-17T08:30:00Z', location: 'Patil Bio-Organic Farm, Sangli', note: '10 Tons turmeric loaded and sealed.' },
      { status: 'IN_TRANSIT', timestamp: '2026-09-17T15:00:00Z', location: 'Pune Bypass Highway', note: 'Vehicle passed toll plaza; ETA on schedule.' },
    ],
  },
];

export const DEMO_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log_1',
    actorUserId: 'usr_admin_1',
    actorRole: 'ADMIN',
    actorName: 'CropLink Admin Operations',
    action: 'USER_APPROVED',
    entity: 'FarmerProfile',
    entityId: 'usr_farmer_1',
    metadata: { reason: 'Documents and land area verified with revenue records.' },
    timestamp: '2026-08-01T11:00:00Z',
  },
  {
    id: 'log_2',
    actorUserId: 'usr_admin_1',
    actorRole: 'ADMIN',
    actorName: 'CropLink Admin Operations',
    action: 'USER_APPROVED',
    entity: 'IndustryProfile',
    entityId: 'usr_industry_1',
    metadata: { reason: 'GSTIN 27AAAAA0000A1Z5 verified active.' },
    timestamp: '2026-08-02T12:00:00Z',
  },
  {
    id: 'log_3',
    actorUserId: 'usr_admin_1',
    actorRole: 'ADMIN',
    actorName: 'CropLink Admin Operations',
    action: 'SAMPLE_VERIFIED',
    entity: 'AuctionLot',
    entityId: 'auc_1',
    metadata: { sampleWeightKg: 20, gradeAssigned: 'Grade A+' },
    timestamp: '2026-09-15T10:00:00Z',
  },
];
